### ISSUE TITLE
[Bug]: casting event SubscriptionPriceNotification to Price throw error

### ISSUE THREAD

**Issue by jobcespedes** [PaddleHQ/paddle-node-sdk#25]
### What happened?

Getting casting error from SubscriptionPriceNotification to Price
```
Type 'SubscriptionPriceNotification' is missing the following properties from type 'Price': createdAt, updatedAt, product
```

### Steps to reproduce

1. Cast from SubscriptionPriceNotification to Price

### What did you expect to happen?

SubscriptionPriceNotification becomes a Price entity for storage purposes
 
### Logs

```shell
Type 'SubscriptionPriceNotification' is missing the following properties from type 'Price': createdAt, updatedAt, product
```

**Comment by vijayasingam-paddle** [comment]
Hello, 
This is similar to #26 , the notification classes and their API counterparts are different by design.

I would recommend updating your function to accept both classes. Worst case, you can manually typecast them to read the fields you need. But be very careful while manually typecasting as you will lose type safety.

Please let us know if we can help you with anything else. 

Thank you.
