### ISSUE TITLE
[Feature]: add error handling example

### ISSUE THREAD

**Issue by jobcespedes** [PaddleHQ/paddle-node-sdk#7]
### Tell us about your feature request

Add an example to handle a particular error response, for instance 409 conflict

### What problem are you looking to solve?

Properly handle a particular error response

### How important is this suggestion to you?

Nice to have

**Comment by vijayasingam-paddle** [comment]
Hi @jobcespedes,
Sorry for the delay in response. 

All of our error messages will be of type [ApiError](https://github.com/PaddleHQ/paddle-node-sdk/blob/main/src/internal/errors/generic.ts) 

You can handle any particular error type within your `catch` block using the `code` property.
For example, to handle [conflict error](https://developer.paddle.com/errors/shared/conflict) 

```
try {
  // Call functions from the SDK
} catch (e: any) {
  // e.code will always follow the error code defined in our documentation
  if (e.code === 'conflict') {
    // Handle Conflict error
  }
}
```

Unfortunately the class `ApiError` is not exported as part of this package, I will fix that shortly so that we can typecast the error object within the `catch` block. 

We will also update our documentation to make this clear.

Please let us know if we can help with anything else. 

Thank you.
