### ISSUE TITLE
[Bug]:  Missing Invoice Webhooks in Paddle Node.js SDK

### ISSUE THREAD

**Issue by Mcoder995** [PaddleHQ/paddle-node-sdk#80]
### What happened?

The Paddle Node.js SDK does not support any webhooks starting with "invoice" (e.g., invoice.issued, invoice.paid,
invoice.overdue, invoice.canceled). These events are essential for handling invoicing workflows but are completely missing from the SDK, making it difficult to process such events natively.

Steps to reproduce

Attempt to configure a webhook in the Paddle Node.js SDK for invoice_payment_succeeded or any other invoice_* event.
Observe that there are no methods or event handlers for these webhooks in the SDK.
Review the SDK documentation and confirm that no reference exists for invoice-related webhooks.

### Steps to reproduce

1. Attempt to configure a webhook in the Paddle Node.js SDK for invoice_payment_succeeded or any other invoice_* event.
2. Observe that there are no methods or event handlers for these webhooks in the SDK.
3. Review the SDK documentation and confirm that no reference exists for invoice-related webhooks.

### What did you expect to happen?

The SDK should provide support for all Paddle webhooks, including those related to invoices, to ensure full compatibility with Paddle's webhook offerings.

### Logs

```shell
N/A — this issue is based on missing functionality in the SDK, not runtime errors.
```

**Comment by danbillson** [comment]
Hi @Mcoder995, thanks for raising this, we'll look into this and provide an update soon

**Comment by danbillson** [comment]
Hi @Mcoder995, we have added implicit support for these events in `2.1.3` (see https://github.com/PaddleHQ/paddle-node-sdk/pull/85)

The SDK does not directly support the invoice events i.e. provide the invoice type enum or types but will now still give you the data from the event instead of returning null

An example of this implementation would be for matching on the event type you can manually add in the invoice event types which will be passed through.
```
    switch (event?.eventType) {
      case EventName.SubscriptionCreated:
           // handle subscribtion created event

      // @ts-ignore
      case "invoice.paid":
          // handle invoice paid event as a generic event
```
Note that the `event?.data` will use camel case for object keys to match the rest of the node-sdk instead of snake case from the raw object.
